# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/Samsung/UnrealEngine
GAMEPROJECTFILE =/home/tyomavader/Documents/Unreal Projects/ChessDev 5.2 5.2/ChessDev.uproject

TARGETS = \
	ChessDev-Linux-DebugGame  \
	ChessDev-Linux-Shipping  \
	ChessDev \
	ChessDevEditor-Linux-DebugGame  \
	ChessDevEditor-Linux-Shipping  \
	ChessDevEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ChessDevEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ChessDevEditor-Linux-Debug


ChessDev-Linux-DebugGame:
	 $(PROJECTBUILD) ChessDev Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChessDev-Linux-Shipping:
	 $(PROJECTBUILD) ChessDev Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChessDev:
	 $(PROJECTBUILD) ChessDev Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChessDevEditor-Linux-DebugGame:
	 $(PROJECTBUILD) ChessDevEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChessDevEditor-Linux-Shipping:
	 $(PROJECTBUILD) ChessDevEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

ChessDevEditor:
	 $(PROJECTBUILD) ChessDevEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
